version: '3.8'
services:
  postgres:
    container_name: postgres-container
    image: postgres
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '5432:5432'
  api:
    container_name: api-container
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build: .
    image: plant-manager-api
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/plant-manager-api/dist
    ports:
      - '8080:8080'
    links:
      - postgres
